### ISSUE TITLE
Storage size of ‘md_ctx’ isn’t known

### ISSUE THREAD

**Issue by DigiAngel** [merces/pev#103]
Topic:
~~~
cd lib/libpe && make all
make[1]: Entering directory '/home//build/pev/lib/libpe'
cc -shared -Wl,-soname,libpe.so.1  -o libpe.so /home//build/pev/lib/libpe/build/./error.o /home/jlay/build/pev/lib/libpe/build/./pe.o
make[1]: Leaving directory '/home//build/pev/lib/libpe'
cd src && make all
make[1]: Entering directory '/home//build/pev/src'
cc -c -o build/./pehash.o pehash.c -I/home//build/pev/lib/libpe -I"../include" -W -Wall -Wextra -std=c99 -pedantic -D_GNU_SOURCE -D_FORTIFY_SOURCE=1 -DSHAREDIR="\"/usr/local/share/pev"\"
pehash.c: In function ‘calc_hash’:
pehash.c:218:13: error: storage size of ‘md_ctx’ isn’t known
  EVP_MD_CTX md_ctx;
             ^~~~~~
pehash.c:224:2: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’ [-Wimplicit-function-declaration]
  EVP_MD_CTX_cleanup(&md_ctx);
  ^~~~~~~~~~~~~~~~~~
pehash.c:218:13: warning: unused variable ‘md_ctx’ [-Wunused-variable]
  EVP_MD_CTX md_ctx;
             ^~~~~~
make[1]: *** [build/./pehash.o] Error 1
Makefile:142: recipe for target 'build/./pehash.o' failed
make[1]: Leaving directory '/home//build/pev/src'
make: *** [all] Error 2
Makefile:9: recipe for target 'all' failed
~~~

Debian version is stretch/sid with gcc version
~~~
gcc (Debian 6.2.1-5) 6.2.1 20161124
~~~

Thank you.

**Comment by jweyrich** [comment]
Which version of `libssl-dev` do you have in the system? You may check with `dpkg -l | grep libssl-dev`.

**Comment by DigiAngel** [comment]
Oh look....1.1.0..no wonder 8-|
~~~
libssl-dev:amd64                      1.1.0c-2
~~~

Guessing that's why yes?  I've not had much luck with anything compiling against 1.1.0 :(  Thank you.

**Comment by jweyrich** [comment]
That's the probable cause. OpenSSL 1.1.0 seem to have changed libcrypto and libssl public structures, causing various problems on various softwares.

I worked on a fix to make it compatible with OpenSSL 1.1.0 and will publish it as soon as I test it. Will let you know. Thanks for the report!

**Comment by DigiAngel** [comment]
Awesome...thank you.

**Comment by jweyrich** [comment]
@DigiAngel did you install libssl-dev 1.1.0 from the unstable apt repository or from source? I don't see another way to have it on Debian right now.

**Comment by jweyrich** [comment]
I've merged the referenced PR to fix the compatibility issues. If you want to give it a try and let us know, we'd appreciate your feedback.

**Comment by DigiAngel** [comment]
Yea that totally fixed it...thank you!

**Comment by jweyrich** [comment]
Awesome! Thank you for the report and feedback!
