### ISSUE TITLE
Port to OpenSSL 1.1?

### ISSUE THREAD

**Issue by petterreinholdtsen** [merces/pev#108]
Hi.  The pev source do not compile when using OpenSSL 1.1.  This is the first build failure:

```
pehash.c: In function 'calc_hash':
pehash.c:218:13: error: storage size of 'md_ctx' isn't known
  EVP_MD_CTX md_ctx;
             ^~~~~~
pehash.c:224:2: warning: implicit declaration of function 'EVP_MD_CTX_cleanup' [-Wimplicit-function-declaration]
  EVP_MD_CTX_cleanup(&md_ctx);
  ^~~~~~~~~~~~~~~~~~
pehash.c:218:13: warning: unused variable 'md_ctx' [-Wunused-variable]
  EVP_MD_CTX md_ctx;
             ^~~~~~
```

Please port pev to the most resent OpenSSL version.

**Comment by jweyrich** [comment]
Hi! The problem you reported was fixed in https://github.com/merces/pev/commit/53eb494baf2b1132d27f73da079f4226157f6381, but we haven't shipped a new release of pev since then, so it's likely you're reporting this issue based on an outdated revision. Until there's a new release, you should be able to install pev from source. If not, then let us know so we can talk about releasing a patch revision to help you out.

**Comment by petterreinholdtsen** [comment]
[Jardel Weyrich]
> Until there's a new release, you should be able to install pev from
> source. If not, then let us know so we can talk about releasing a
> patch revision to help you out.

Thank you for the update.  I tested using version 0.80 while preparing
it for Debian.  I did not as you suspect use the latest git source.

A new release with OpenSSL 1.1 support would make the life of pev
maintainers in Debian easier. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by jweyrich** [comment]
@merces Do you think you'd be able to release a minor revision soon?

**Comment by petterreinholdtsen** [comment]
The request for OpenSSL 1.1 support in Debian is tracked as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870779 .

**Comment by jweyrich** [comment]
@petterreinholdtsen just wanted to let you know that we've released 0.81 last week.

**Comment by petterreinholdtsen** [comment]
[Jardel Weyrich]
> @petterreinholdtsen just wanted to let you know that we've released
> 0.81 last week.

Thank you for the heads up.  Is there any news on OpenSSL 1.1?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by merces** [comment]
Hi @petterreinholdtsen. We really appreciate your interest and efforts spent on this. Thanks a lot for reaching out. @jweyrich and I will work on it tomorrow and update this issue later this week.

**Comment by jweyrich** [comment]
> [Jardel Weyrich]
> > @petterreinholdtsen just wanted to let you know that we've released
> > 0.81 last week.
> 
> Thank you for the heads up.  Is there any news on OpenSSL 1.1?
> 
> -- 
> Happy hacking
> Petter Reinholdtsen
> 
Yes. It includes changes to support OpenSSL 1.1. Mostly https://github.com/merces/pev/commit/53eb494baf2b1132d27f73da079f4226157f6381

**Comment by petterreinholdtsen** [comment]
Good to know.  Did not see it mentioned in the ChangeLog, hence my question. :)

**Comment by merces** [comment]
> Did not see it mentioned in the ChangeLog

My fault. Just fixed that. ;-)
