### ISSUE TITLE
Binary garbage on stderr when open() fails

### ISSUE THREAD

**Issue by jwilk** [merces/pev#111]
```
$ pescan nonexistent
ERROR [-15]: open() failed (°xˇ´ľuˇé[ˇWoˇ)
```

Tested with git master (ccef80d9092d4762344d3f4f527f1986b678562d).

**Comment by jweyrich** [comment]
Ouch! That looks ugly. That output comes from https://github.com/merces/libpe/blob/cbc1a47a86ad81f2f8ad96d51894ab678797fbe5/error.c#L62, and it looks like `strerror_r` is not doing it job correctly (or maybe we aren't).

According to the documentation:

> The strerror() and the GNU-specific strerror_r() functions return the appropriate error description string, or an "Unknown error nnn" message if the error number is unknown.

I believe even if the supplied size isn't enough to hold the resulting message, it would not fail like that. But I might be wrong.

Finally, I wasn't able to reproduce it. Could you provide more details about your platform? Linux on i386, amd64? Which compiler+version?

**Comment by jwilk** [comment]
The important part of `strerror_r` manpage seems to be:

> The GNU‐specific strerror_r() returns a pointer to a string containing the error message. This may be either a pointer to a string that the function stores in *buf*, or a pointer to some (immutable) static string (in which case *buf* is unused).

So the buffer you pass to `strerror_r` may remain uninitialized.

I tested this on Linux, i386, GCC 6, glibc 2.24.

**Comment by jweyrich** [comment]
Although it also mentions the following right after the sentences you quoted:

> If the function stores a string in buf, then at most buflen bytes are stored (the string may be truncated if buflen is too small and errnum is unknown). **The string always includes a terminating null byte.**

It seems that the GNU-specific version is picked by the compiler and it doesn't seem to do what I did expect. We could simply `memset` the buffer before usage, but it may silence the relevant error message that should appear there.

Will have to investigate it during the weekend. Please let me know about your findings if you chase this before me.

**Comment by jweyrich** [comment]
Hi @jwilk! I wasn't able to reproduce the issue but I think I've fixed it. Your quote from the docs makes total sense. Thanks!
Would you mind testing it again?
