### ISSUE TITLE
peres uses uninitialized memory

### ISSUE THREAD

**Issue by jwilk** [merces/pev#122]
Apparently `peres` assumes that memory from `malloc()` is zero-initialized.
It crashes on some files when this assumption is violated:

    $ printf 'MZ%058d\200\0\0\0%064dPE\0\0%03d\0%016d\v\1%090d\20\0\0\0%016d\0%d\0\0%0160d\0%d\0\0%04d\0\f\0\0%02648d' > crash.exe
    $ export MALLOC_PERTURB_=165
    $ peres -i crash.exe 
    Segmentation fault

Backtrace:

    #0  freeNodes (currentNode=0x5a5a5a5a) at peres.c:271
    #1  0x80001886 in discoveryNodesPeres (ctx=<optimized out>) at peres.c:731
    #2  0x800022ae in main (argc=3, argv=0xbffff654) at peres.c:769

Tested with git master (e9f7c2d855b852d7c52653ec4e0c251a29b1e3dd).

Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

**Comment by jweyrich** [comment]
@jwilk thank you for the report!
