### ISSUE TITLE
Why does 'readpe' need write permissions?

### ISSUE THREAD

**Issue by hunt3vil** [merces/pev#124]
Hi! Currently running `readpe` from pev 0.70 on the SANS SIFT Workstation and I've come across what I consider odd functionality: running `readpe sample.exe` where `sample.exe` is owned by `root:root` with permissions 644 fails. I ran a quick `strace` (see below) and noticed that `readpe` attempts to open the file with write permissions. I would expect it to only need read permissions so as to not unintentionally modify the sample.

```bash
...SNIP... 
munmap(0x7f731e009000, 160182)          = 0
brk(0)                                  = 0x155c000
brk(0x157d000)                          = 0x157d000
open("sample.exe", O_RDWR)            = -1 EACCES (Permission denied)
write(2, "ERROR [-14]: fdopen() failed (\350\265"..., 38ERROR [-14]: fdopen() failed (���s)
) = 38
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by merces** [comment]
I believe it doesn't. We probably left it like this because we planned to have writing operations in the future (for i.e. being able to add a section to a PE file) but that's something we've never achieved. For v0.70 you'd need to recompile libpe (using [this tree](https://github.com/merces/libpe/tree/7015c904d063e334103fccc5929d0cb17ce72c1e)) with the following patch applied:

```
diff --git a/pe.c b/pe.c
index a6f29f6..f599b05 100644
--- a/pe.c
+++ b/pe.c
@@ -45,7 +45,7 @@ pe_err_e pe_load_file_ext(pe_ctx_t *ctx, const char *path, pe_options_e options)
        }

        // Open the file.
-       const int fd = open(ctx->path, O_RDWR);
+       const int fd = open(ctx->path, O_RDONLY);
        if (fd == -1) {
                //perror("open");
                return LIBPE_E_OPEN_FAILED;
@@ -72,7 +72,7 @@ pe_err_e pe_load_file_ext(pe_ctx_t *ctx, const char *path, pe_options_e options)
        ctx->map_size = stat.st_size;

        // Create the virtual memory mapping.
-       ctx->map_addr = mmap(NULL, ctx->map_size, PROT_READ|PROT_WRITE,
+       ctx->map_addr = mmap(NULL, ctx->map_size, PROT_READ,
                MAP_SHARED, fd, 0);
        if (ctx->map_addr == MAP_FAILED) {
                close(fd);
```

Then you'd have it working for binaries with no writing permission:

```
user@linux64:~/pev-0.70$ chmod 0400 ~/winapp/PUTTY.EXE
user@linux64:~/pev-0.70$ /usr/bin/readpe --header coff ~/winapp/PUTTY.EXE

COFF/File header
Machine:                         0x14c IMAGE_FILE_MACHINE_I386
Number of sections:              4
Date/time stamp:                 1446891460 (Sat, 07 Nov 2015 10:17:40 UTC)
Symbol Table offset:             0
Number of symbols:               0
Size of optional header:         0xe0
Characteristics:                 0x10f
                                 IMAGE_FILE_RELOCS_STRIPPED
                                 IMAGE_FILE_EXECUTABLE_IMAGE
                                 IMAGE_FILE_LINE_NUMS_STRIPPED
                                 IMAGE_FILE_LOCAL_SYMS_STRIPPED
                                 IMAGE_FILE_32BIT_MACHINE
```

We have no time to fix it, test and make a release. Indeed, we haven't had time to work on pev recently. v0.80 still has lots of bugs. :disappointed:

**Comment by jweyrich** [comment]
That behaviour was changed in v0.80 (now it opens as readonly unless you specify via a flag that you want RW ops). @Merces is right. We still have various bugs and we need to improve our test suite to cover all already known/reported bugs, and start creating new cases for each new scenario.
