### ISSUE TITLE
Invalid JSON output for "Optional/Image header"."DLL characteristics names"

### ISSUE THREAD

**Issue by torandu** [merces/pev#127]
Output includes invalid JSON for DLL characteristics names. I found that in some cases there is a leading comma in the array. In other cases, there is a trailing comma.

Example with leading comma:
```
$ readpe -f json -h optional l64pq.dll
{
    "Optional/Image header": {
        "Magic number": "0x20b (PE32+)",
        "Linker major version": "12",
        "Linker minor version": "0",
        "Size of .text section": "0x1d600",
        "Size of .data section": "0xf800",
        "Size of .bss section": "0",
        "Entrypoint": "0x1df68",
        "Address of .text section": "0x1000",
        "ImageBase": "0x180000000",
        "Alignment of sections": "0x1000",
        "Alignment factor": "0x200",
        "Major version of required OS": "5",
        "Minor version of required OS": "2",
        "Major version of image": "0",
        "Minor version of image": "0",
        "Major version of subsystem": "5",
        "Minor version of subsystem": "2",
        "Size of image": "0x30000",
        "Size of headers": "0x400",
        "Checksum": "0",
        "Subsystem required": "0x3 (IMAGE_SUBSYSTEM_WINDOWS_CUI)",
        "DLL characteristics": "0x120",
        "DLL characteristics names": [
,
            "IMAGE_DLLCHARACTERISTICS_NX_COMPAT"
        ],
        "Size of stack to reserve": "0x400000",
        "Size of stack to commit": "0x1000",
        "Size of heap space to reserve": "0x100000",
        "Size of heap space to commit": "0x1000"
    }
}
$ readpe -f json -h optional l64pq.dll | python -mjson.tool
Expecting value: line 26 column 1 (char 965)
```

Example snippet with trailing comma:
```
        "DLL characteristics names": [
            "IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE",
            "IMAGE_DLLCHARACTERISTICS_NX_COMPAT",

        ],
```

In both cases, the resulting JSON is invalid.

**Comment by jweyrich** [comment]
Hm.. that's interesting. Thanks for reporting! Could you send us a binary sample (just link for download) that causes any of these cases?

**Comment by torandu** [comment]
Example is here
https://gist.github.com/torandu/f0529204d4d34f4543fa4c08b5018c45

**Comment by rhaist** [comment]
I can confirm this behavior with the following file:

http://the.earth.li/\~sgtatham/putty/0.70/w64/putty.exe

Also there maybe should be an output default for this:
```
    "Imported functions": [
export directory not found
    ],
```

**Comment by wesinator** [comment]
Should look at using [Jansson](https://github.com/akheron/jansson) for JSON output.

**Comment by jweyrich** [comment]
> I can confirm this behavior with the following file:
> 
> [http://the.earth.li/\~sgtatham/putty/0.70/w64/putty.exe](http://the.earth.li/%5C~sgtatham/putty/0.70/w64/putty.exe)
> 
> Also there maybe should be an output default for this:
> 
> ```
>     "Imported functions": [
> export directory not found
>     ],
> ```

That was fixed - it was an output generated by debug that shouldn't be there.

**Comment by jweyrich** [comment]
> Example is here
> https://gist.github.com/torandu/f0529204d4d34f4543fa4c08b5018c45

Would you be able to provide the binary sample again? The link is broken right now.

**Comment by jweyrich** [comment]
@torandu: I believe the commit referenced above fixes the original issue.

@rhaist: the issue you reported was caused by a debug message that shouldn't be present. It was fixed by https://github.com/merces/pev/commit/7891e1acae740890821271946408094b823f3984
