### ISSUE TITLE
cyggcc_s-1.dll missing error

### ISSUE THREAD

**Issue by quantran13** [merces/pev#128]
I downloaded the pre-compiled binaries for Windows, but when I tried running `pehash.exe` from the command line it says `The program can't start because cyggcc_s-1.dll is missing from your computer`. I installed Cygwin and the packages listed on the README file but the error still happens.

I'm running on Windows 7 by the way.

**Comment by merces** [comment]
Hi @quantran13. Thanks for reporting this. I could not reproduce this error, though. Are you using v0.80? It ran normally here.

**Comment by philippelyp** [comment]
cyggcc_s-1.dll was not installed with Cygwin for me.  I guess that the presence of the dll depends on the version and/or packages that you are installing.

**Comment by merces** [comment]
This dependency was removed. We'll consider it fixed as the current code compiles correctly with Cygwin.
