### ISSUE TITLE
How to handle with the error  "undefined symbol: pe_can_read"?

### ISSUE THREAD

**Issue by PointerWild** [merces/pev#129]
here is the error message:
peres: symbol lookup error: peres: undefined symbol: pe_can_read

here is the command i used :
peres -i /tmp/analysisDown/xiaookjfsky.exe

BTW, there are some msg :
root@roy-virtual-machine:~/下载# peres -V /tmp/analysisDown/xiaookjfsky.exe
peres from pev 0.80 <http://pev.sf.net> toolkit .....

I use pev 0.80, and i also install pev 0.70-amd64.deb.
my computer is ubuntu 16.0.4.

**Comment by VolodymyrB** [comment]
Same

**Comment by merces** [comment]
Can you guys provide the binary files that triggered the said bug?

**Comment by jweyrich** [comment]
I'm closing the issue due to inactivity. If you are able to reproduce it, feel free to reopen it and share your steps.
