### ISSUE TITLE
readpe segfault

### ISSUE THREAD

**Issue by cynicer** [merces/pev#132]
Hey everyone,

I'm new to this tool and wanted to try it on some old binary (Ferentus.exe: PE32 executable (GUI) Intel 80386, for MS Windows) I had lying around.
[Ferentus.exe.zip](https://github.com/merces/pev/files/2066131/Ferentus.exe.zip)

When I execute `readpe -A Ferentus.exe` or `readpe Ferentus.exe` I get a `Segmentation fault: 11`. I guess this is not the normal behaviour?

Regards,
Marcel

**Comment by merces** [comment]
Hi @cynicer. You are right, this is not the normal behaviour. What version are you using? Did you try compiling pev from the the latest source code available? I tried it here and readpe works with this binary.

Thanks!

**Comment by cynicer** [comment]
Hey @merces,

I used the macOS version installed via brew. I just used a compiled version from the latest source available and I get the same result  (`Segmentation fault: 11`).

Regards,
Marcel

**Comment by merces** [comment]
Humm.. I've tested with the latest source code from this repository and it works with your binary. Maybe the brew package maintainer needs to update it?

**Comment by jweyrich** [comment]
Hi @cynicer!

I just tried using the latest code (commit 8ecd6bb4ca7031ea08257accd0898dd330b03d36) on macOS (10.14.6) and couldn't reproduce it.

Please, can you tried it again?
