### ISSUE TITLE
Different imphash result from pefile

### ISSUE THREAD

**Issue by issueraise** [merces/pev#143]
Hi,

I was checking the latest version (compiled today, April 2, 2019) and noticed a different imphash result from pefile.

I tried hashing this file https://cygwin.com/setup-x86_64.exe (ae481452927771af871e218c85252192e1448c48fbc54bfe38c1bd2303af4ad0)

For reference, here are the hashes for the same file on VirusTotal:
https://www.virustotal.com/gui/file/ae481452927771af871e218c85252192e1448c48fbc54bfe38c1bd2303af4ad0/details

pefile outputs **6991b4f5b1a464addc0d4394358fe5ec** and pehash is outputting  **e1b077f3c4f31373328c815a0fefa795**

pehash setup-x86_64.exe
file
    filepath:                        setup-x86_64.exe
    md5:                             ebf71ebf6c671238bcb023b91d25971c
    sha1:                            1e414c51ace0ca87b8e3bd0cd67948d00435da7e
    sha256:                          ae481452927771af871e218c85252192e1448c48fbc54bfe38c1bd2303af4ad0
    ssdeep:                          24576:c3P0KIHbODPB6fvn4Jl3a/Q1bL3igdvkaPqzQ+jt6/37bO532fne+7:c27OgoUWbbfPuU+532Pew
    imphash:                         **e1b077f3c4f31373328c815a0fefa795**

**Comment by merces** [comment]
Thanks for reporting this. I'll be fixed soon!

**Comment by merces** [comment]
Fixed by https://github.com/merces/libpe/commit/a88e6f21436c9237da5e2831b4a8888b56be0e15
