### ISSUE TITLE
Filepath not escaped resulting in an invalid json on Windows

### ISSUE THREAD

**Issue by philippelyp** [merces/pev#144]
Using pehash, on Windows, with json output, `\` is not escaped in the filepath resulting in an invalid json.

For example:
```
    "file": {
        "filepath": "C:\Windows\System32\wbem\xml\wmi2xml.dll",
        "md5": "b1757cc102d0c3082f4048e94de653cc",
```

Should be:
```
    "file": {
        "filepath": "C:\\Windows\\System32\\wbem\\xml\\wmi2xml.dll",
        "md5": "b1757cc102d0c3082f4048e94de653cc",
```

**Comment by jweyrich** [comment]
Thank you for the report @philippelyp!
I just added an encoding table for JSON entities such as `\`. This change should address filesystem paths well, but doesn't handle all possible JSON entities such as some control codes.
Let me know if it works for you.

**Comment by jweyrich** [comment]
FWIW, the JSON output now escapes all control codes.
