### ISSUE TITLE
Segfault 11 on binary

### ISSUE THREAD

**Issue by paulmand3l** [merces/pev#145]
Getting a segfault when trying to run readpe on the attached dll (it's ostensibly a gatt table generation library from Sierra Wireless, but run at your own risk, of course).

I'm on OSX Mohave and just installed pev via homebrew (following the instructions in the PEV documentation - http://pev.sourceforge.net/doc/manual/en_us/ch02.html#binmac)

[db_gen.dll.zip](https://github.com/merces/pev/files/3370330/db_gen.dll.zip)

**Comment by jweyrich** [comment]
Hi @paulmand3l!

1. In which version of pev did you notice this crash?
2. In which system are you running it?

I wasn't able to reproduce the crash on macOS using the latest commit - we should release a new version soon.

**Comment by asutoshpalai** [comment]
I installed pev via brew and saw Segfault 11 when running `readpe -d <someexe>` in the `output_open_scope` function. It was a `mov eax, [0x8]` instruction which I assume is in someway malformed.

I build from the source via `brew` and saw the same segfault (didn't debug to check which instruction). Then I built the `HEAD` using `brew install --build-from-source --HEAD pev --debug` and ignored the failed patch and it worked like charm.

**Comment by jweyrich** [comment]
Thank you for the reply.
Indeed, this is a bug in v0.80 which appears depending on the binary being analysed. It was fixed a while ago - that's why the HEAD works.
The brew package should be fixed as soon as we release a new version.
@merces: do you think we're able to release v0.81 or maybe v0.90 before xmas?

**Comment by merces** [comment]
Considering 2020 Christmas, yes we will. 😁
I already started working on this. 😉

**Comment by merces** [comment]
Fixed on the latest release ([v0.81](https://github.com/merces/pev/releases/tag/v0.81)).
