### ISSUE TITLE
peres failed with some dll files

### ISSUE THREAD

**Issue by tw-ascohen** [merces/pev#153]
**Describe the bug**
Resources exist but output is:
WARNING: this file has no resources

**To Reproduce**
Please provide us with:
- pev 0.81
- Centos7
- PCL4RES.DLL
- ./peres -a PCL4RES.DLL

**Expected behavior**
show resources

**Screenshots**

**Additional context**
Suggested fix is:
https://github.com/merces/pev/files/4586001/peres.c.diff.txt
[peres.c.diff.txt](https://github.com/merces/pev/files/4586001/peres.c.diff.txt)

[PCL4RES.DLL.zip](https://github.com/merces/pev/files/4585964/PCL4RES.DLL.zip)

**Comment by jweyrich** [comment]
Thanks for you report @tw-ascohen!

It seems that we fixed it in https://github.com/merces/pev/commit/7bbe21e1ebd98a60434dd051c6a0a3ff347267fa
