### ISSUE TITLE
build failed in windows

### ISSUE THREAD

**Issue by danperor** [merces/pev#169]
cd lib/libpe && make all
make[1]: Entering directory '/cygdrive/d/code/gitcode/pev/lib/libpe'
cc -c -O2 -ffast-math -I"./include" -fPIC -W -Wall -Wextra -pedantic -std=c99 -c -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -o /cygdrive/d/code/gitcode/pev/lib/libpe/build/./error.o error.c
/bin/sh: cc: command not found
make[1]: *** [Makefile:114: /cygdrive/d/code/gitcode/pev/lib/libpe/build/./error.o] Error 127
make[1]: Leaving directory '/cygdrive/d/code/gitcode/pev/lib/libpe'
make: *** [Makefile:9: all] Error 2

**Comment by merces** [comment]
Hello. Thanks for raising this issue. :)

Are you trying to build using Cygwin? Please see [here](https://github.com/merces/pev/wiki/Installation#how-to-build-on-windows-via-cygwin).

Cheers,
Fernando

**Comment by merces** [comment]
I'll close it for now. The author can reopen in case the link I provided is not enough to fix the problem.
