### ISSUE TITLE
Compiling with flat namespace causes build for Homebrew to fail

### ISSUE THREAD

**Issue by n-thumann** [merces/pev#170]
Hi ✌🏻
The build for Homebrew fail (see https://github.com/Homebrew/homebrew-core/pull/88460) due to the compiling with flat namespace.
Can you fix this issue?

**Comment by merces** [comment]
Hi @n-thumann. Thanks for raising this issue, however, I am not familiar with the concept of flat namespaces. Is it something we should add to the Makefile for macOS? Could you help?

Thanks!

**Comment by n-thumann** [comment]
Unfortunately me neither 😬 But I've found out that omitting `-flat_namespace` here
https://github.com/merces/pev/blob/master/src/plugins/Makefile#L69 and https://github.com/merces/libpe/blob/master/Makefile#L105 solves the issue. TBH, I cannot evaluate if or how this affects your application.

**Comment by merces** [comment]
Oh, I see. I didn't know we were explicitly asking for it. It was probably asked by whoever worked on the macOS build (it wasn't me). I'll run a few tests without to see how the application behaves. Thanks!

**Comment by merces** [comment]
@jweyrich do you game any objections to it?

**Comment by carlocab** [comment]
Some background about this flag and why it's a good idea to remove it can be found here: ocaml/ocaml#10723

Though, the TL;DR is: you only need this if you support *very* old Macs (pre-10.5 running PPC, so about 15 years old).

**Comment by merces** [comment]
Thanks. It should be fixed now.
