### ISSUE TITLE
peres extract resources(.ico) without the head of ico

### ISSUE THREAD

**Issue by ghost** [merces/pev#74]

**Comment by merces** [comment]
Hi @ajiaiscas sorry about the long delay and thanks for reporting this. The thing is peres extracts the raw resources but icons are split when compiled into resources and need to be reconstructed. We'll investigate for a possible solution.

**Comment by jweyrich** [comment]
@merces Look! I think we already knew that! haha

**Comment by jweyrich** [comment]
Probably fixed by https://github.com/merces/pev/commit/465cd8b1e93a3c08c0a216dcf2be32d2385fc86d.
