### ISSUE TITLE
peres does not read shuffled resources

### ISSUE THREAD

**Issue by struppigel** [merces/pev#77]
1. Get the file resource_shuffled.exe from corkami, BinaryCorpus_v2.zip: https://code.google.com/p/corkami/downloads/detail?name=BinaryCorpus_v2.zip&can=2&q=
2. Execute: 
   peres -i resource_shuffled.exe

The output is:
    this file has no resources

The output should be something like: 
    address: 0x12f0, size: 0x229, language -> ID: 0, name -> ID: 101, type -> ID: RT_RCDATA
(extracted info with another tool)

**Comment by jweyrich** [comment]
I don't see an easy way to identify which directory is in which position since that is defined/guaranteed by their order/index.

We could traverse all directories, but `IMAGE_DATA_DIRECTORY` gives us only `VirtualAddress` and `Size` before we access the `VirtualAddress` (translated to an offset) to read an specific directory structure.

That would require a brute-force detection, or maybe I'm missing something.

**Comment by merces** [comment]
Hum... @katjahahn do you know a tool that can read it correctly? I'd like to see its source code. 🙂

**Comment by katjahahn** [comment]
I used PortEx: https://github.com/katjahahn/PortEx/tree/master/src/main/java/com/github/katjahahn/parser/sections/rsrc
However, it seems the resource_shuffled.exe is not in the corkami project anymore, so I cannot confirm that it works with the current version.

**Comment by lacostej** [comment]
Does this help?
http://pedump.me/401ed03adc85aa46708994cb5dbb7a89/ ?

It looks one could recreate the exe from http://pedump.me/401ed03adc85aa46708994cb5dbb7a89/#hexdump

**Comment by merces** [comment]
It should still be available [here](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/corkami/BinaryCorpus_v2.zip) from [this archive](https://code.google.com/archive/p/corkami/downloads?page=4). 😉

**Comment by katjahahn** [comment]
PortEx does work with that file.

**Comment by GoGoOtaku** [comment]
PortEx ignores the directory table size entry all together. It seems like Windows also ignores it for at least resources which isn't too weird as it is sort of redundant. Commenting out the early return in `pe_resource_base_ptr` makes it work correctly and overall seems to not break anything from what I could tell.

**Comment by merces** [comment]
Fixed by https://github.com/merces/libpe/pull/39
