### ISSUE TITLE
Release libpe under LGPL

### ISSUE THREAD

**Issue by tklengyel** [merces/pev#85]
Hello,
I just found your code and it's really great! Any chance you could release the libpe component under LGPL license? I would love to use it within the LibVMI project to replace our own home-baked version of parsing PEs.

Thanks,
Tamas

**Comment by merces** [comment]
Hi @tklengyel. Sorry about the long delay. We had it in mind already so your request came right in time. libpe is now under LGPLv3. We look forward to see it working with your project! Thank you!

**Comment by tklengyel** [comment]
Excellent, thanks!

**Comment by jweyrich** [comment]
Awesome! :+1:
