### ISSUE TITLE
All reported export functions have the same name

### ISSUE THREAD

**Issue by LigH-de** [merces/pev#89]
I checked a just compiled x265 v1.7+298 EXE and DLL built with GCC 4.8.2 or 4.9.2 with different PE analyzers for whether they export functions.

In contrast to PE Scanner and Dependency Walker, which report all exported functions with unique names, the list of exported functions reported by readpe contains the same name for all exported functions.

    Exported functions
    0x2af000:                        x265_api_get_63
    0x1c:                            x265_api_get_63
    0x36cd36ad:                      x265_api_get_63
    0x36e336d8:                      x265_api_get_63
    0x36f936ee:                      x265_api_get_63
    0x370f3704:                      x265_api_get_63
    0x3f66:                          x265_api_get_63
    0x2b0000:                        x265_api_get_63
    0x1c:                            x265_api_get_63
    0x310a30ff:                      x265_api_get_63
    0x31203115:                      x265_api_get_63
    0x3136312b:                      x265_api_get_63
    0x314c3141:                      x265_api_get_63
    0x31b3:                          x265_api_get_63
    0x2b2000:                        x265_api_get_63
    0x26c:                           x265_api_get_63
    0x344733a6:                      x265_api_get_63
    0x3454344e:                      x265_api_get_63
    0x3462345b:                      x265_api_get_63
    0x34703469:                      x265_api_get_63
    0x347e3477:                      x265_api_get_63
    0x348c3485:                      x265_api_get_63
    0x349d3493:                      x265_api_get_63

A link to this x265 build will be published in the doom9 and videohelp forums if you need the binaries to check.

**Comment by jweyrich** [comment]
Interesting. Which version of pev did you run?

**Comment by LigH-de** [comment]
Version 0.70, still the latest pre-built binary from SourceForge (2013-12-27).

**Comment by merces** [comment]
Could you please test with the latest code here in Github?

**Comment by LigH-de** [comment]
I can't make a new build yet, I don't have experience in setting up a cygwin build environment. To compile x265, I just use prepared MSYS/MinGW environments, but wouldn't know how to create one.

You can download several x265 builds (v1.7+3xx, min. 3 MB) from https://www.mediafire.com/folder/6lfp2jlygogwa/HEVC and check the x265_ml.exe's (multi-lib) in each flavour.

In the last 64-bit build (v1.7+399), readpe v0.70 does not even find any exports, while PES redects them reliably.

In fact, the multi-lib exe files should possibly even export a triple set of functions, because they contain libx265 in 3 variants (with 8, 10, and 12 bit internal precision). The encoder call will select them via the parameter '-D/--output-depth 8|10|12'.

More details can be found on the following sites or forums:
http://x265.org/
https://bitbucket.org/multicoreware/x265
http://x265.readthedocs.org/
http://forum.videohelp.com/threads/360069-x265-HEVC-Encoder
http://forum.videohelp.com/threads/357754-%5BHEVC%5D-x265-EXE-mingw-builds
http://forum.doom9.org/showthread.php?t=168814

**Comment by LigH-de** [comment]
I tried to set up a cygwin environment and build pev by calling "make" in the src subdirectory. But it failed due to a missing pe,h file.

**Comment by merces** [comment]
Thanks, for the sharing the samples. I'll have a look into it asap.
Yes, we have some [documentation](http://pev.sourceforge.net/doc/manual/en_us/ch02s02.html) sorry for not referencing it in GitHub. This is something we have to fix as well. :)

**Comment by LigH-de** [comment]
Cloning the default branch from your git repo recursively provided the required sources to pass the compilation, I copied the exe files and plugins after "make" and "make install" from /usr/local/{bin|lib/pev} and updated the required cyg*.dll's from /bin; this package already worked well and reported the expected import tables for both Win32 and Win64 multi-lib exe's of x265 v1.7+399.

Will try now with the v0.70-fixes branch ...

**Comment by jweyrich** [comment]
Nice! The 0.70-fixes branch is out-of-date as we should have already merged it against master a few months ago. Master is the latest source right now.

**Comment by merces** [comment]
I've merged both branches yesterday but I've applied some patches on v0.70-fixes already. Apart from that, this branch is using the latest version of libpe. The differences are small, but still exist. ;)

Yes, the git call is correct

**Comment by LigH-de** [comment]
OK, the v70-fixes build works just as well.

**Comment by merces** [comment]
Hi @LigH-de just ran a test with latest source code from v0.70-fixes branch and the result was the following:

```
$ src/build/readpe -e ~/libx265_main12.dll 
Exported functions
    Function
        0x5a800:                         x265_api_get_64
    Function
        0x5a8c0:                         x265_api_query
    Function
        0x3c8840:                        x265_build_info_str
    Function
        0x5a580:                         x265_cleanup
    Function
        0x5a7a0:                         x265_encoder_close
    Function
        0x5a490:                         x265_encoder_encode
    Function
        0x5a560:                         x265_encoder_get_stats
    Function
        0x5a2a0:                         x265_encoder_headers
    Function
        0x59ec0:                         x265_encoder_log
    Function
        0x59ef0:                         x265_encoder_open_64
    Function
        0x5a5c0:                         x265_encoder_parameters
    Function
        0x5a340:                         x265_encoder_reconfig
    Function
        0x3e33f8:                        x265_max_bit_depth
    Function
        0x38a7c0:                        x265_param_alloc
    Function
        0x35720:                         x265_param_apply_profile
    Function
        0x38a7e0:                        x265_param_default
    Function
        0x38ad00:                        x265_param_default_preset
    Function
        0x38a7d0:                        x265_param_free
    Function
        0x38bcc0:                        x265_param_parse
    Function
        0x5a5b0:                         x265_picture_alloc
    Function
        0x59eb0:                         x265_picture_free
    Function
        0x5a690:                         x265_picture_init
    Function
        0x3c8848:                        x265_version_str
```

I'm closing this issue then. We'll release the next version ASAP so it will include this fix. Please, feel free to comment / request for reopening this issue if you feel something is wrong. Thanks a lot for your time and great help! :)

**Comment by LigH-de** [comment]
The interesting part was about testing the x265_ml.exe, not the DLLs, though... ;)

**Comment by merces** [comment]
Really interesting. I just ran the tests again with those x265_ml.exe and everything is good so far. I'll definitely include these binaries into the test set. :thumbsup:
