### ISSUE TITLE
Making a distribution ZIP archive for cygwin fails

### ISSUE THREAD

**Issue by LigH-de** [merces/pev#96]
Despite the (probably outdated) [source installation guide](http://pev.sourceforge.net/doc/manual/en_us/ch02s02.html), ```make zip``` fails, ```Makefile``` does not contain a target "zip".

Instead it contains a target "win"; but this fails too, at this file: ```/usr/bin/cyggcc_s-1.dll``` does not exist in current cygwin-win32 installations; instead, there is a ```cyggcc_s-seh-1.dll``` (which seems to serve now the same purpose).

**Comment by merces** [comment]
Thanks for reporting this. Actually the existing documentation is for [v0.70](https://github.com/merces/pev/releases/tag/v0.70) release, that has a 'zip' target. We changed that In the  current code, that is going to be part of our furutre v0.80 release.

Regarding the cyggcc_s-1.dll, apparently cygwin doesn't require it anymore to run our pev programs, so I have removed it.

Again, thank you very much for letting us know about this bug. We really appreciate. ;)
