### ISSUE TITLE
How to get File Version info with recent version of pev tools???

### ISSUE THREAD

**Issue by dgonyier** [merces/pev#97]
I've used the pev 0.40 tool to get file version information quite easily from a windows PE file with

``` bash
$ pev -p jre-8u92-windows-i586.exe
8.0.920.14
$ pev -p jre-8u92-windows-x64.exe
8.0.920.14
```

With the most recent version of the toolkit, I can't figure out how simply get the File Version field from a PE file. The pev tool is gone, and there is nothing in the current documentation that says specifically how to do this.

**Comment by merces** [comment]
pev has suffered many changes and among all of them, we forgot to keep this option. Actually it should be in peres tool, but it is not and the main developer of peres stopped to contribute for some reason, so we now have a resources problem, sorry, I don't see this option being implemented anytime soon unless someone with C coding (and PE) skills joins the project.

However, you still have access to [older versions of pev in SF](https://sourceforge.net/projects/pev/files/), including v0.22, the first public version which its unique feature was to print File Version, and of course v.40 that you are used to. ;)

Thanks for your message.

**Comment by rdoeffinger** [comment]
Maybe this could at least be added to the documentation?
Changing a tool to be completely incompatible with the old version and not at all providing the one feature it had but keeping the same name for the project seems rather unfortunate and not at all user-friendly.
Plus it leaves us without a solution to the problem that the project originally tried to solve...

**Comment by rdoeffinger** [comment]
Also, there is no tag for v0.40 either it seems.

**Comment by merces** [comment]
@rdoeffinger you are right and we are very sorry about that. Please notice pev was my first open source project and I have to admit I had no experience with either programming or open source project management at the time. I'd never do that today but in the past I did. :grimacing:

Alternatively, pev 0.40 is available for download, including its source code [here](https://sourceforge.net/projects/pev/files/pev-0.40/). You can get the File Version structure with the **-p** option as you can see below:

```
$ tar xf pev-0.40.tar.gz

$ cd pev-0.40

$ make
gcc -Wall -O2 -ansi  -o pev src/pev.c src/parser.c src/modules/tls.c

$ ./pev -v
pev 0.40

$ ./pev -p ~/winapp/PUTTY.EXE
0.66.0.0
```

We'll keep this issue open until we have time (or we receive a gently collaboration) to put this feature into pev again. I don't have the necessary tools to update the documentation right now, but I'll try to fix ti asap.

Thanks for giving your insights here. When we see people are using pev, it really motivates us to move on.

**Comment by rdoeffinger** [comment]
Sorry if I was a bit aggressive in my comment, my point is not to lay blame.
I think things would be a bit smoother if the pev-legacy (as I'll call it now) was in git as well, both so you don't need to send people to download it separately and in case someone really relies on it they still could send fixes for it (personally, I switched to strings and grep for now, which currently works for my purposes).
Do I understand right that there is no history under some kind of source control for versions before 0.4?
Even if so, it should be possible to get a partial history by extracting and committing the tar file contents to a separate pev-legacy branch (for example) and setting tags.
If you don't have time I can do that and send a pull request, as long as that would be something you'd merge.

**Comment by merces** [comment]
Don't worry, you were not.

As you thought, there was no version control before 0.50 indeed. I'd appreciate if you could do this. Also, have a look at the latest commits. I think I fixed the problem of printing the File Version number with peres -v swtich.

**Comment by rdoeffinger** [comment]
peres -v works, though compared to "pev -p" it prints "File Version:" and not only the version, though it doesn't matter much.
About importing the old versions, I have some concerns...
- at least the 0.22 tar file contains pev binaries, and 2 different ones at that. Which also results in "make" saying there is nothing to do. Not sure what to do about that best?
- the 0.30 tar file contains a .svn directory, so that code was under version control, more specifically: svn+ssh://nandu88@svn.code.sf.net/p/pev/code
Did that repo contain anything useful (probably not since it's at revision 1)? Does it maybe still exist somewhere or could be restored?
I tried "rsync -av svn.code.sf.net::p/pev/code ." but it seems it is gone at least from there, and "rsync -av PROJECTNAME.svn.sourceforge.net::svn/PROJECTNAME/* ." is only a completely empty repo.
I think I'll remove the binaries and .svn etc. directories from the tar files before committing.

**Comment by rdoeffinger** [comment]
It's not possible to make a pull request for a new branch, but you can do this:
git fetch git@github.com:rdoeffinger/pev.git pev-legacy --tags
git push origin FETCH_HEAD:pev-legacy --tags -n

(remove the -n if it looks like it is pushing the right things to actually push the new branch along with the tags)
Tell me if you want me to change something, like the author name on the commits or so.

**Comment by merces** [comment]
I added the "File Version" string to have a consistent CSV/HTML/XML output as well.

I agree with deleting the binaries, for sure.

This SVN repository is likely gone, unfortunately.

I was able to fetch your branch but I couldn't push it onto the repository. See below:

```
$ git push origin FETCH_HEAD:pev-legacy --tags -n
error: unable to push to unqualified destination: pev-legacy
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'git@github.com:merces/pev.git'
```

Does that help if I create a branch called pev-legacy?

**Comment by rdoeffinger** [comment]
Yes, if you create the branch (as en empty branch!) I can likely send a pull request.
I didn't test the push command, but by the error message this one should work:
git push origin FETCH_HEAD:refs/heads/pev-legacy --tags -n

**Comment by merces** [comment]
Done! Thank you again! I'm closing this issue as I readded the feature with @948b830c9824. ;)
